name: Generate 3D Contribution (daily)

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D profile contribution
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          username: therunnas
          theme: night-rainbow

      - name: Move generated svgs to assets/3d-contrib
        run: |
          mkdir -p assets
          rm -rf assets/3d-contrib
          mv profile-3d-contrib assets/3d-contrib
          ls -la assets/3d-contrib

      - name: Auto commit generated SVGs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(3d): update contribution svgs"
